RUBY_ROOT=/opt/elasticbeanstalk/lib/ruby
PATH=/opt/elasticbeanstalk/lib/ruby/bin:$PATH

export RUBY_GC_HEAP_INIT_SLOTS=50000
export RUBY_HEAP_FREE_MIN=10000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_HEAP_SLOTS_INCREMENT=10000
export RUBY_GC_MALLOC_LIMIT=10000000
